FROM python:3.11.6

WORKDIR /rosie

COPY requirements.txt .

COPY dispatch.py .
COPY callmanager.py .
COPY rosie_utils.py .
COPY speechsynth_azure.py .
COPY voiceassistant.py .
COPY ./templates ./templates

ARG AZURE_SPEECH_KEY
ARG AZURE_SPEECH_REGION
ARG SERVICE_PORT
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG OPENAI_API_KEY

ENV AZURE_SPEECH_KEY=$AZURE_SPEECH_KEY
ENV AZURE_SPEECH_REGION=$AZURE_SPEECH_REGION
ENV SERVICE_PORT=$SERVICE_PORT
ENV TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
ENV TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
ENV OPENAI_API_KEY=$OPENAI_API_KEY

RUN echo "The AZURE_SPEECH_KEY variable is $AZURE_SPEECH_KEY"
RUN echo "The AZURE_SPEECH_REGION variable is $AZURE_SPEECH_REGION"
RUN echo "The SERVICE_PORT variable is $SERVICE_PORT"
RUN echo "The TWILIO_ACCOUNT_SID variable is $TWILIO_ACCOUNT_SID"
RUN echo "The OPENAI_API_KEY variable is $OPENAI_API_KEY"

RUN pip install -r requirements.txt

EXPOSE 8080
EXPOSE 4040

CMD ["python", "./dispatch.py"]